name: Development Workflow
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Running tests..."
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Running build..."
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Running deployment..."
